name: Android CI Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      # یہ سٹیپ لاگ میں پرنٹ کرے گا کہ فائل کس فولڈر میں بنی ہے
      - name: List Generated Files
        run: find . -type f \( -name "*.apk" -o -name "*.aab" \)

      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: '**/build/outputs/**/*.apk'
          if-no-files-found: warn
